interface PredictionData {
  eligible: boolean;
  probability: number;
  reason?: string;
  recommendations?: string[];
  timestamp?: Date;
}

export const generatePDFReport = (prediction: PredictionData, userEmail: string) => {
  // Create a simple HTML document for the PDF
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Loan Eligibility Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #333;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .title {
      color: #2563eb;
      font-size: 28px;
      margin-bottom: 10px;
    }
    .status {
      font-size: 24px;
      font-weight: bold;
      margin: 20px 0;
      padding: 15px;
      border-radius: 8px;
      text-align: center;
    }
    .eligible {
      background-color: #dcfce7;
      color: #166534;
    }
    .not-eligible {
      background-color: #fee2e2;
      color: #991b1b;
    }
    .section {
      margin: 20px 0;
      padding: 15px;
      background-color: #f8fafc;
      border-radius: 8px;
    }
    .section-title {
      font-size: 18px;
      font-weight: bold;
      color: #2563eb;
      margin-bottom: 10px;
    }
    .info-row {
      margin: 8px 0;
      display: flex;
      justify-content: space-between;
    }
    .label {
      font-weight: 600;
    }
    .recommendations {
      list-style-type: none;
      padding: 0;
    }
    .recommendations li {
      padding: 8px;
      margin: 5px 0;
      background-color: #fff;
      border-left: 4px solid #2563eb;
      padding-left: 15px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      font-size: 12px;
      color: #64748b;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">Loan Eligibility Report</div>
    <div>AI-Powered Loan Advisory System</div>
  </div>

  <div class="status ${prediction.eligible ? 'eligible' : 'not-eligible'}">
    ${prediction.eligible ? '✅ Eligible for Loan' : '❌ Not Eligible for Loan'}
  </div>

  <div class="section">
    <div class="section-title">Report Details</div>
    <div class="info-row">
      <span class="label">User Email:</span>
      <span>${userEmail}</span>
    </div>
    <div class="info-row">
      <span class="label">Report Date:</span>
      <span>${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</span>
    </div>
    <div class="info-row">
      <span class="label">Eligibility Probability:</span>
      <span>${(prediction.probability * 100).toFixed(1)}%</span>
    </div>
  </div>

  ${prediction.reason ? `
  <div class="section">
    <div class="section-title">Analysis</div>
    <p>${prediction.reason}</p>
  </div>
  ` : ''}

  ${prediction.recommendations && prediction.recommendations.length > 0 ? `
  <div class="section">
    <div class="section-title">Recommendations</div>
    <ul class="recommendations">
      ${prediction.recommendations.map(rec => `<li>${rec}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  <div class="footer">
    <p>This report is generated by an AI system for advisory purposes only.</p>
    <p>Loan Eligibility System © ${new Date().getFullYear()}</p>
  </div>
</body>
</html>
  `;

  // Create a Blob and download it
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `loan-eligibility-report-${new Date().getTime()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
